### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by elvispoz** [berettavexee/events-scrapper#5]
Traceback (most recent call last):
  File "C:\xampp\htdocs\fb\events-scrapper-master\events-scraper.py", line 448, in <module>
    headless=args.headless)
  File "C:\xampp\htdocs\fb\events-scrapper-master\events-scraper.py", line 80, in __init__
    options=FireFoxOptions,)
  File "C:\Users\mariuszm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\mariuszm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\mariuszm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\mariuszm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mariuszm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by berettavexee** [comment]
Hello, 

It seems to be a Selenium bug due to some environment where Selenium and/or Geckodrive can't find the Firefox binary.

Here is the selenium bug report:
https://github.com/SeleniumHQ/selenium/issues/3884

I'm closing this bug because I can't replicate it and it's not related to the script.
